### ISSUE TITLE
Crash to desktop on loading/creating world

### ISSUE THREAD

**Issue by evadw** [DArkHekRoMaNT/TeleportationNetwork#12]
### Mod Version

1.10.0

### Game Version

1.18

### OS

Windows

### Play mode

Singleplayer

### Problem

I can get the game to function normally if I disable all my mods, load a world with only teleportation network (and commonlib) and THEN enable all my other mods after launching the game, but then it breaks when i restart my computer. I've done a lot of testing, so if you need more information, let me know

### Logs

```bash
Running on 64 bit Windows with 24 GB RAM 
Game Version: v1.18.0-rc.2 (Unstable)
4/6/2023 4:23:47 PM: Critical error occurred in the following mod: tpnet@1.10.0
Loaded Mods: weaponpacka@1.2.4, tonwexp@1.1.0, backpackpackplus@1.0.3, composter@1.0.3, foundrymod@1.0.0, weaponpackg@1.0.1, hideandfabric@1.2.7, nooffhandhunger@1.0.0, plantmat@1.4.0, potontheshelf@1.0.0, primitivesurvival@3.1.5, qptech@, quickerbarrel@1.1.0, ropebucket@1.0.0, sortablestorage@1.8.0, spidersilk@1.2.2, superfuel@2.0.7, game@1.18.0-rc.2, animalcages@2.1.1, betterfirepit@1.0.0, carryon@1.0.0-rc.1, commonlib@2.0.2, khat@1.0.0, lichen@1.6.1, medievalexpansion@3.9.0, ovenfuel@1.0.0, petai@1.6.0, claywheel@1.0.1, resinlightsbymad@1.0.1, creative@1.18.0-rc.2, vsquest@0.2.0, survival@1.18.0-rc.2, vsvillage@0.7.1, xlib@0.7.0-pre.3, xmelee@0.0.10, xrowboat@0.0.5, bullseye@2.5.0-pre.2, em@2.0.0-pre.5, feverstonehorses@1.4.1, foxtaming@1.0.0-pre.1, glassmaking@1.3.4, stickcrafting@1.0.0, tpnet@1.10.0, wolftaming@1.6.0, xskills@0.7.0-pre.5, bricklayers@2.0.0-pre.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at TeleportationNetwork.TeleportMapLayer.Render(GuiElementMap mapElem, Single dt) in TeleportationNetwork/System/TeleportManager/TeleportMapLayer.cs:line 33
   at Vintagestory.GameContent.GuiElementMap.RenderInteractiveElements(Single deltaTime) in VSEssentials\Systems\WorldMap\GuiElementMap.cs:line 64
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 711
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.GameContent.GuiDialogWorldMap.OnRenderGUI(Single deltaTime) in VSEssentials\Systems\WorldMap\GuiDialogWorldMap.cs:line 276
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 302
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 201
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 785
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 963
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 241
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 722
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/6/2023 11:09:26 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1600522529444488113, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 642c31fe
P4: mscorlib
P5: 4.8.4614.0
P6: 63995ad2
P7: 462d
P8: 8
P9: System.TypeLoadException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER82DC.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_e8a2577af746de19b49eb283cb1439505113dfe4_749552bb_40b38dd5-cd48-4931-942e-55d4a33097b9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2127635a-efbd-45ca-9911-095093fe1988
Report Status: 268435456
Hashed bucket: 7f076a7329851f5b263632c2b68c63b1
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/6/2023 11:09:25 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.0.0
P3: 642c31fe
P4: mscorlib
P5: 4.8.4614.0
P6: 63995ad2
P7: 462d
P8: 8
P9: System.TypeLoadException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_e8a2577af746de19b49eb283cb1439505113dfe4_749552bb_40b38dd5-cd48-4931-942e-55d4a33097b9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2127635a-efbd-45ca-9911-095093fe1988
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/6/2023 11:09:24 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.0.0, time stamp: 0x642c31fe
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2728, time stamp: 0xe7e53a4e
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x458
Faulting application start time: 0x01d968997c073b8e
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2127635a-efbd-45ca-9911-095093fe1988
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by DArkHekRoMaNT** [comment]
What do you have in client-main.txt and server-main.txt?

**Comment by DArkHekRoMaNT** [comment]
Apparently the config was not loaded correctly. Perhaps some crash or error in CommonLib before

**Comment by evadw** [comment]
[client-main.txt](https://github.com/DArkHekRoMaNT/TeleportationNetwork/files/11182310/client-main.txt)
[server-main.txt](https://github.com/DArkHekRoMaNT/TeleportationNetwork/files/11182311/server-main.txt)
here you go!

**Comment by DArkHekRoMaNT** [comment]
Conflict with ViesCraft
```
6.4.2023 16:29:47 [Error] [commonlib] An exception was thrown when trying to start the mod: System.TypeLoadException: Method 'get_MountPoints' in type 'viescraftmachines.src.common.entity.EntityMountable' from assembly 'viescraftmachines, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at CommonLib.Config.ConfigManager.<StartPre>g__GetAllTypesWithAttribute|8_1[T]() in CommonLib/Config/ConfigManager.cs:line 75 at CommonLib.Config.ConfigManager.<StartPre>g__LoadAllConfigs|8_0() in CommonLib/Config/ConfigManager.cs:line 50 at CommonLib.Config.ConfigManager.StartPre(ICoreAPI api) in CommonLib/Config/ConfigManager.cs:line 33 at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\ModLoader.cs:line 617
```
