### ISSUE TITLE
Doesn't support net7 build

### ISSUE THREAD

**Issue by Colubin** [DArkHekRoMaNT/TeleportationNetwork#16]
### Mod Version

1.12.1

### Game Version

.net7 Experimental build 1.18.6

### OS

Windows

### Play mode

Singleplayer

### Problem

Game crashes at the end of loading a save, just before you'd expect the game to start. Tested on mod version 1.12.0 just in case, runs a different error but still crashes. 

Save loads correctly once TPnetwork is turned off. 

### Logs

```bash
Running on 64 bit Windows with 16319 MB RAM
Game Version: .net7 Experimental build - v1.18.6 (Unstable)
08/07/2023 10.44.48: Critical error occurred in the following mod: tpnet@1.12.1
Loaded Mods: aculinaryartillery@1.0.12-pre.2, betterdrifters@2.1.3, composter@1.0.4, fieldsofgold@2.1.6, indappledgroves@0.4.9-rc.8, TA_plainsandvalleys@1.0.3, primitivesurvival@3.2.2, sfaws@1.0.0, specializedbags-18Slot@0.4.2, game@1.18.6, wildcrafttrees@1.2.3, wildcraft@1.6.6, beehivekiln@1.2.2, betterfirepit@1.1.0, canjewelry@0.1.10, cbetterfertilizer@1.0.1, commonlib@2.1.1, expandedfoods@1.6.6, fromgoldencombs@1.4.16-rc.2, grassiergrass@1.0.0, medievalexpansion@3.9.3, metaltongs@1.0.1, morepiles@1.4.1, prospectorinfo@4.3.0, statushud@1.2.3, stonebakeoven@1.0.3, creative@1.18.6, vsquest@0.4.1, survival@1.18.6, vsvillage@0.7.2, xlib@0.7.2, bullseye@2.5.0-rc.1, tpnet@1.12.1, biggerwindmill@0.3.0, xskills@0.7.3, wildcraftxskillspatch@0.2.0
System.TypeLoadException: Could not load type 'MonoMod.Utils.Extensions' from assembly '0Harmony, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at TeleportationNetwork.TeleportList.SetFrom(TeleportList points)
   at TeleportationNetwork.TeleportManager.<StartPre>b__10_2(SyncTeleportListMessage msg) in TeleportationNetwork/System/TeleportManager/TeleportManager.cs:line 33
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkChannel.cs:line 73
   at Vintagestory.Client.NoObf.NetworkChannel.OnPacket(Packet_CustomPacket p) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkChannel.cs:line 27
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkAPI.cs:line 106
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 73
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 300
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 127
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 08/07/2023 10.40.53, Site = , Source = Windows Error Reporting, Message = Fault bucket 1880357656339671929, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB83B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBBD6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBBE7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBBE7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBC07.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_429d1884e4154ce84ac24791dbb411b784966a1e_a47ecedf_2a26a584-17f5-428c-9bae-7105e3b3ab83

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8c37133-dbf9-43e0-a6bc-b51bafbe121f
Report Status: 268566528
Hashed bucket: 0e6a3f4f1527bf7a2a185f536ccfeb79
Cab Guid: 0 }
--------------
{ TimeGenerated = 08/07/2023 10.40.50, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x638f99ee
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3c88
Faulting application start time: 0x01d9b16ef726b08d
Faulting application path: D:\Vintage Story\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintage Story\Vintagestory\Lib\openal32.dll
Report Id: d8c37133-dbf9-43e0-a6bc-b51bafbe121f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 08/07/2023 10.40.40, Site = , Source = Windows Error Reporting, Message = Fault bucket 2084645821209844142, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: KERNELBASE.dll
P5: 10.0.19041.3086
P6: e1ac3f79
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER84A8.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER88D0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER88E0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER88DE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER88FF.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f101424365f721ec513af82fe82b3f33749f09c_a47ecedf_45f0d3b9-5af0-4dd8-8e74-f5c3f7945a50

Analysis symbol: 
Rechecking for solution: 0
Report Id: 53d9c60a-5404-4e47-a8a9-852c4a742d81
Report Status: 268566528
Hashed bucket: dd785e69536ac262fcee265457b719ae
Cab Guid: 0 }
```

**Comment by DArkHekRoMaNT** [comment]
The mod doesn't support net7 right now. Will be later

**Comment by DArkHekRoMaNT** [comment]
Should work with 1.13.0 . Don't forget to update CommonLib to 2.2.0
