### ISSUE TITLE
Crash when opening gui

### ISSUE THREAD

**Issue by DrasticLp** [DArkHekRoMaNT/TeleportationNetwork#17]
### Mod Version

1.14.3

### CommonLib Version

2.3.7

### Game Version

1.19.7

### OS

Windows

### Play mode

Multiplayer

### Problem

I'm hosting my own server (with one friend) and I am the only one of us that crashes when opening the edit gui (shift click on "teleporter")
The mod list is in the logs
My friend doesn't crash tho.
I'm on windows11_64x

Config:
Ryzen 5 7640hs
RTX 4050
16gb ram (ddr5)
Nvme gen 4 ssd so speed isn't an issue

### Logs

```bash
Game Version: v1.19.7 (Stable)
01/05/2024 22:12:16: Critical error occurred
Loaded Mods: bettercrates@1.7.0, extrachests@1.8.0, qptech@1.15.1, Swordz@1.1.6, game@1.19.7, wildcrafttrees@1.2.4, wildcraft@1.6.6, alchemy@1.6.32, betterruins@0.3.5, carryon@1.7.4, commonlib@2.3.7, petai@2.2.4, playerlist@1.8.1, rpgdifficulty@1.0.0, rustboundmagic@1.7.4, storagecontroller@1.0.9, trailmod@1.0.7, creative@1.19.7, survival@1.19.7, vsvillage@1.0.0-pre.3, wildfarmingrevival@1.1.9, xlib@0.8.3-pre.1, betterruinslootchanges@0.0.3, cats@2.0.1, feverstonehorses@1.6.1, feverstonewilds@1.4.5, floating-landmasses@1.0.6, playercorpse@1.9.0, tpnet@1.14.3, wolftaming@2.1.2, xskills@0.8.5-pre.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Mat4f.Multiply(Single[] output, Single[] a, Single[] b) in VintagestoryApi\Math\Matrix\Mat4f.cs:line 340
   at Vintagestory.API.Common.AnimationFrame.FinalizeMatrices(Dictionary`2 jointsById) in VintagestoryApi\Common\Model\Animation\AnimationFrame.cs:line 58
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 116
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 353
   at Vintagestory.API.Common.PlayerAnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Entity\PlayerAnimationManager.cs:line 34
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.7 (Stable)
01/05/2024 22:17:07: Critical error occurred in the following mod: tpnet@1.14.3
Loaded Mods: bettercrates@1.7.0, extrachests@1.8.0, qptech@1.15.1, Swordz@1.1.6, game@1.19.7, wildcrafttrees@1.2.4, wildcraft@1.6.6, alchemy@1.6.32, betterruins@0.3.5, carryon@1.7.4, commonlib@2.3.7, petai@2.2.4, playerlist@1.8.1, rpgdifficulty@1.0.0, rustboundmagic@1.7.4, storagecontroller@1.0.9, trailmod@1.0.7, creative@1.19.7, survival@1.19.7, vsvillage@1.0.0-pre.3, wildfarmingrevival@1.1.9, xlib@0.8.3-pre.1, betterruinslootchanges@0.0.3, cats@2.0.1, feverstonehorses@1.6.1, feverstonewilds@1.4.5, floating-landmasses@1.0.6, playercorpse@1.9.0, tpnet@1.14.3, wolftaming@2.1.2, xskills@0.8.5-pre.1
System.ArgumentNullException: Value cannot be null. (Parameter 'Asset Data is null. Is the asset loaded?')
   at Vintagestory.Client.NoObf.SvgLoader.rasterizeSvg(IAsset svgAsset, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 154
   at Vintagestory.Client.NoObf.SvgLoader.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 74
   at Vintagestory.Client.NoObf.GuiAPI.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\API\GuiAPI.cs:line 58
   at Vintagestory.GameContent.WaypointMapLayer.<>c__DisplayClass18_1.<.ctor>b__2(Context ctx, Int32 x, Int32 y, Single w, Single h, Double[] rgba) in VSEssentials\Systems\WorldMap\WaypointLayer\WaypointMapLayer.cs:line 118
   at Vintagestory.API.Client.IconUtil.DrawIconInt(Context cr, String type, Int32 x, Int32 y, Single width, Single height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 119
   at Vintagestory.API.Client.GuiElementIconListPicker.DrawElement(String icon, Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementIconListPicker.cs:line 22
   at Vintagestory.API.Client.GuiElementElementListPickerBase`1.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementElementListPickerBase.cs:line 65
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 434
   at TeleportationNetwork.GuiDialogEditTeleport.ComposeDialog() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 137
   at TeleportationNetwork.GuiDialogEditTeleport.TryOpen() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 58
   at TeleportationNetwork.BlockEntityTeleport.OpenEditDialog() in TeleportationNetwork/BlockEntity/Teleport/BlockEntityTeleport.cs:line 272
   at TeleportationNetwork.BlockTeleport.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in TeleportationNetwork/Block/BlockTeleport.cs:line 94
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.7 (Stable)
01/05/2024 22:18:24: Critical error occurred in the following mod: tpnet@1.14.3
Loaded Mods: bettercrates@1.7.0, extrachests@1.8.0, qptech@1.15.1, Swordz@1.1.6, game@1.19.7, wildcrafttrees@1.2.4, wildcraft@1.6.6, alchemy@1.6.32, betterruins@0.3.5, carryon@1.7.4, commonlib@2.3.7, petai@2.2.4, playerlist@1.8.1, rpgdifficulty@1.0.0, rustboundmagic@1.7.4, storagecontroller@1.0.9, trailmod@1.0.7, creative@1.19.7, survival@1.19.7, vsvillage@1.0.0-pre.3, wildfarmingrevival@1.1.9, xlib@0.8.3-pre.1, betterruinslootchanges@0.0.3, cats@2.0.1, feverstonehorses@1.6.1, feverstonewilds@1.4.5, floating-landmasses@1.0.6, playercorpse@1.9.0, tpnet@1.14.3, wolftaming@2.1.2, xskills@0.8.5-pre.1
System.ArgumentNullException: Value cannot be null. (Parameter 'Asset Data is null. Is the asset loaded?')
   at Vintagestory.Client.NoObf.SvgLoader.rasterizeSvg(IAsset svgAsset, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 154
   at Vintagestory.Client.NoObf.SvgLoader.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 74
   at Vintagestory.Client.NoObf.GuiAPI.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\API\GuiAPI.cs:line 58
   at Vintagestory.GameContent.WaypointMapLayer.<>c__DisplayClass18_1.<.ctor>b__2(Context ctx, Int32 x, Int32 y, Single w, Single h, Double[] rgba) in VSEssentials\Systems\WorldMap\WaypointLayer\WaypointMapLayer.cs:line 118
   at Vintagestory.API.Client.IconUtil.DrawIconInt(Context cr, String type, Int32 x, Int32 y, Single width, Single height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 119
   at Vintagestory.API.Client.GuiElementIconListPicker.DrawElement(String icon, Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementIconListPicker.cs:line 22
   at Vintagestory.API.Client.GuiElementElementListPickerBase`1.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementElementListPickerBase.cs:line 65
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 434
   at TeleportationNetwork.GuiDialogEditTeleport.ComposeDialog() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 137
   at TeleportationNetwork.GuiDialogEditTeleport.TryOpen() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 58
   at TeleportationNetwork.BlockEntityTeleport.OpenEditDialog() in TeleportationNetwork/BlockEntity/Teleport/BlockEntityTeleport.cs:line 272
   at TeleportationNetwork.BlockTeleport.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in TeleportationNetwork/Block/BlockTeleport.cs:line 94
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.7 (Stable)
01/05/2024 22:21:21: Critical error occurred in the following mod: tpnet@1.14.3
Loaded Mods: bettercrates@1.7.0, extrachests@1.8.0, qptech@1.15.1, Swordz@1.1.6, game@1.19.7, wildcrafttrees@1.2.4, wildcraft@1.6.6, alchemy@1.6.32, betterruins@0.3.5, carryon@1.7.4, commonlib@2.3.7, petai@2.2.4, playerlist@1.8.1, rpgdifficulty@1.0.0, rustboundmagic@1.7.4, storagecontroller@1.0.9, trailmod@1.0.7, creative@1.19.7, survival@1.19.7, vsvillage@1.0.0-pre.3, wildfarmingrevival@1.1.9, xlib@0.8.3-pre.1, betterruinslootchanges@0.0.3, cats@2.0.1, feverstonehorses@1.6.1, feverstonewilds@1.4.5, floating-landmasses@1.0.6, playercorpse@1.9.0, tpnet@1.14.3, wolftaming@2.1.2, xskills@0.8.5-pre.1
System.ArgumentNullException: Value cannot be null. (Parameter 'Asset Data is null. Is the asset loaded?')
   at Vintagestory.Client.NoObf.SvgLoader.rasterizeSvg(IAsset svgAsset, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 154
   at Vintagestory.Client.NoObf.SvgLoader.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 74
   at Vintagestory.Client.NoObf.GuiAPI.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\API\GuiAPI.cs:line 58
   at Vintagestory.GameContent.WaypointMapLayer.<>c__DisplayClass18_1.<.ctor>b__2(Context ctx, Int32 x, Int32 y, Single w, Single h, Double[] rgba) in VSEssentials\Systems\WorldMap\WaypointLayer\WaypointMapLayer.cs:line 118
   at Vintagestory.API.Client.IconUtil.DrawIconInt(Context cr, String type, Int32 x, Int32 y, Single width, Single height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 121
   at Vintagestory.API.Client.IconUtil.DrawIcon(Context cr, String type, Double x, Double y, Double width, Double height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 104
   at Vintagestory.API.Client.GuiElementIconListPicker.DrawElement(String icon, Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementIconListPicker.cs:line 22
   at Vintagestory.API.Client.GuiElementElementListPickerBase`1.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementElementListPickerBase.cs:line 65
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 434
   at TeleportationNetwork.GuiDialogEditTeleport.ComposeDialog() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 137
   at TeleportationNetwork.GuiDialogEditTeleport.TryOpen() in TeleportationNetwork/Gui/GuiDialogEditTeleport.cs:line 58
   at TeleportationNetwork.BlockEntityTeleport.OpenEditDialog() in TeleportationNetwork/BlockEntity/Teleport/BlockEntityTeleport.cs:line 272
   at TeleportationNetwork.BlockTeleport.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in TeleportationNetwork/Block/BlockTeleport.cs:line 94
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

### Mods

```bash
bettercrates@1.7.0
extrachests@1.8.0
qptech@1.15.1
Swordz@1.1.6
game@1.19.7
wildcrafttrees@1.2.4
wildcraft@1.6.6
alchemy@1.6.32
betterruins@0.3.5
carryon@1.7.4
commonlib@2.3.7
petai@2.2.4
playerlist@1.8.1
rpgdifficulty@1.0.0
rustboundmagic@1.7.4
storagecontroller@1.0.9
trailmod@1.0.7
creative@1.19.7
survival@1.19.7
vsvillage@1.0.0-pre.3
wildfarmingrevival@1.1.9
xlib@0.8.3-pre.1
betterruinslootchanges@0.0.3
cats@2.0.1
feverstonehorses@1.6.1
feverstonewilds@1.4.5
floating-landmasses@1.0.6
playercorpse@1.9.0
tpnet@1.14.3
wolftaming@2.1.2
xskills@0.8.5-pre.1
```

**Comment by DArkHekRoMaNT** [comment]
Can you send me client-main.txt? Before restarting the game after the crash

**Comment by DrasticLp** [comment]
Here it is
[client-main.txt](https://github.com/DArkHekRoMaNT/TeleportationNetwork/files/15186099/client-main.txt)

**Comment by DArkHekRoMaNT** [comment]
> Here it is [client-main.txt](https://github.com/DArkHekRoMaNT/TeleportationNetwork/files/15186099/client-main.txt)

Is this the whole log? There must be more. It also resets after restarting the game, so I need a log after the crash

**Comment by DrasticLp** [comment]
My bad here's another log file
[client-main.txt](https://github.com/DArkHekRoMaNT/TeleportationNetwork/files/15203268/client-main.txt)

I didn't rerun the game so idk why it was almost empty

**Comment by Lolithia** [comment]
I had the same issue with the shift+click to open the GUI. I'm running **Teleportation Network 1.14.3** and **Game Version 1.19.8**. I messed around a bit and found out we have a mod in common that seems to be causing the issue. That mod being **CarryOn 1.7.4**.

I noticed that the shift+click to open the teleporter GUI works as normal without CarryOn. With CarryOn enabled, the GUI seems to crash. I messed around a bit and noticed that If you were to open the GUI through your map, shift+click to open the GUI seems to work as intended.
The same also applied when I opened the GUI in any way without CarryOn then turn it back on.
