### ISSUE TITLE
Doesn't load in Windows with 1.17.0-rc.5

### ISSUE THREAD

**Issue by bluelightning32** [DArkHekRoMaNT/TeleportationNetwork#3]
The mod loads in Linux with Mono, but not in Windows with the Microsoft .net runtime. The crash report in Windows says there is a missing block. Really all of the blocks are missing, because the mod didn't load at all. For reference, this is the Windows crash report:
```
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: ancienttools@1.4.5, backpackpack@1.0.3, bettercrates@1.4.2, cavecontent@1.0.1, chiseltools@1.5.4-pre.1, extrachests@1.5.2, fancydoors@1.1.1, weaponpackg@1.0.1, hideandfabric@1.2.5, instruments@1.1.2, moremetals@1.0.9, moreroads@1.4.3, primitivesurvival@3.0.5, qptech@1.10.3-pre.5, rustandrails@1.0.1-pre.1, stackables@2.0.5, locustmod@2.3.5, tradeomat@1.6.1, viescraftmachines@1.17.2, game@1.17.0-rc.5, wildcraft@1.3.1, zeekea@1.6.1, alchemy@1.6.4, egocaribautomapmarkers@2.4.0-pre.1, carrycapacity@0.6.5, fromgoldencombs@1.3.14-pre.1, lichen@1.6.1, medievalexpansion@3.7.1, petai@1.5.3, playercorpse@1.4.1, sluicefork@1.0.0, stonequarry@2.0.0-pre.5, creative@1.17.0-rc.5, survival@1.17.0-rc.5, xmelee@0.0.10, xrowboat@0.0.3, bricklayers@1.0.0-pre.3, bullseye@2.4.0-pre.2, cats@1.5.1, magicmushrooms@1.0.0, feverstonehorses@1.2.9, wolftaming@1.5.2
8/20/2022 3:48:41 PM: Critical error occurred
System.Exception: Don't know how to instantiate block of class 'BlockBrokenTeleport' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\ClassRegistry.cs:line 129
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\BlockTypeNet.cs:line 20
   at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 527
   at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 449
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 416
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The mod did not load because `TeleportationNetwork.BlockPosArrayAttribute` is missing the Clone function.
```
20.8.2022 15:48:24 [Error] [tpnet] Exception thrown when attempting to retrieve all types of the assembly TeleportationNetwork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Vintagestory.Common.ModContainer.GetModSystems(Assembly assembly) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\ModContainer.cs:line 428, InnerException: . Will ignore asssembly. Loader exceptions:
20.8.2022 15:48:24 [Error] [tpnet] System.TypeLoadException: Method 'Clone' in type 'TeleportationNetwork.BlockPosArrayAttribute' from assembly 'TeleportationNetwork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
20.8.2022 15:48:24 [Error] [tpnet] An exception was thrown when trying to load assembly:
System.Exception: C:\Users\tori\AppData\Roaming\VintagestoryData\Cache\unpack\TeleportationNetwork_v1.16.5_v1.6.0.zip_6fbc17aa98f6\TeleportationNetwork.dll declared as code mod, but there are no .dll files that contain at least one ModSystem or has a ModInfo attribute
   at Vintagestory.Common.ModContainer.LoadAssembly(ModCompilationContext compilationContext, ModAssemblyLoader loader) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\ModContainer.cs:line 344
```

`BlockPosArrayAttribute` implements `IAttribute`. The official source code for [IAttribute](https://github.com/anegostudios/vsapi/blob/a176dfee9e62bf16487434702cbbd463123857fc/Datastructures/AttributeTree/Other/IAttribute.cs) does not list a `Clone` function, but that's just because the source has not been updated. Disassembling VintagestoryAPI.dll from 1.17.0-rc.5 shows that the last function in `IAttribute` is `Clone`.
```
[kyle-minecraft@mihoshi vintagestory]$ ikdasm VintagestoryAPI.dll
...
.class interface public abstract auto ansi Vintagestory.API.Datastructures.IAttribute
{
  .method public hidebysig newslot abstract virtual 
          instance void  ToBytes([mscorlib]System.IO.BinaryWriter 'stream') cil managed
  {
  } // end of method IAttribute::ToBytes

  .method public hidebysig newslot abstract virtual 
          instance void  FromBytes([mscorlib]System.IO.BinaryReader 'stream') cil managed
  {
  } // end of method IAttribute::FromBytes

  .method public hidebysig newslot abstract virtual 
          instance int32  GetAttributeId() cil managed
  {
  } // end of method IAttribute::GetAttributeId

  .method public hidebysig newslot abstract virtual 
          instance [mscorlib]System.Type 
          GetType() cil managed
  {
  } // end of method IAttribute::GetType

  .method public hidebysig newslot abstract virtual 
          instance object  GetValue() cil managed
  {
  } // end of method IAttribute::GetValue

  .method public hidebysig newslot abstract virtual 
          instance string  ToJsonToken() cil managed
  {
  } // end of method IAttribute::ToJsonToken

  .method public hidebysig newslot abstract virtual 
          instance bool  Equals(class Vintagestory.API.Common.IWorldAccessor worldForResolve,
                                class Vintagestory.API.Datastructures.IAttribute attr) cil managed
  {
  } // end of method IAttribute::Equals

  .method public hidebysig newslot abstract virtual 
          instance class Vintagestory.API.Datastructures.IAttribute 
          Clone() cil managed
  {
  } // end of method IAttribute::Clone

} // end of class Vintagestory.API.Datastructures.IAttribute
...
```

**Comment by DArkHekRoMaNT** [comment]
Fixed in 1.7.0
